spring.application.name=video

spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8081
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

server.tomcat.max-swallow-size=-1
server.tomcat.max-http-form-post-size=500000000

jwt.secret=your-super-secret-key-here-which-is-very-long-1234567890
jwt.expiration=86400000

cloudinary.cloud_name=dad00zly4
cloudinary.api_key=341341767323921
cloudinary.api_secret=VlDh1bOfDxNMkjkEmKF6qgfSqnc
