spring.application.name=subscription

spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8082

jwt.secret=your-super-secret-key-here-which-is-very-long-1234567890
jwt.expiration=86400000

spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.group-id=subscription-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.value.default.type=com.yt.backend.subscription.model.UserDeletedEvent
spring.kafka.consumer.properties.spring.json.trusted.packages=*
